### ISSUE TITLE
Error on running on kali linux

### ISSUE THREAD

**Issue by mananjain61** [souzomain/Shaco#2]
my teamserver and shaco handler is running on a server  which is different from where i run my havoc client
so while building the binary using the havoc client i get this error
[*] initializing
[-] compiler not found
![image](https://github.com/souzomain/Shaco/assets/17821270/2fd927b7-4767-4549-8fdb-bcff13bda1bf)

**Comment by mananjain61** [comment]
![image](https://github.com/souzomain/Shaco/assets/17821270/4b1efbd9-12c6-403d-8e22-ddb2b5b4efba)
i solved that by installing clang
but i'm not getting any connection even on running the payload generated

**Comment by mananjain61** [comment]
i generated a binary file using the shaco agent
but on executing that i didn't receive the connection on my server

**Comment by mananjain61** [comment]
![image](https://github.com/souzomain/Shaco/assets/17821270/a7fe272d-7744-4b82-9546-49387bec06d8)
![image](https://github.com/souzomain/Shaco/assets/17821270/55971164-c667-4f4b-bd52-b4dadad5158c)
see it is generated successfully
but on execution on my target linux server
i don't get any connection or any message like agent connected
![image](https://github.com/souzomain/Shaco/assets/17821270/46477dc9-9db3-4c1e-94aa-0ce7190e2acc)

**Comment by souzomain** [comment]
I understand, but the shaco is in daemon mode

![image](https://github.com/souzomain/Shaco/assets/92044641/f8ac51e4-c16c-49df-987c-de68f422d0c3)

in havoc, you don't see any connection from shaco?
if not, you configured the python api correctely?
you compiled in x86 or other arch?
try disable daemon mode to see the error.

**Comment by mananjain61** [comment]
how to solve this??
i compiled in x64 architecture

**Comment by souzomain** [comment]
fixed in the latest update
