### ISSUE TITLE
Websocket error: Handshake Status 404 Not Fount

### ISSUE THREAD

**Issue by skyf4lling** [souzomain/Shaco#6]
Hello,

After cloning the Shaco Repo and installing the necessary websocket-client for Python, I'm receiving the following error after running the `handler.py`

`[-] Websocket error: Handshake status 404 Not Found -+-+- {'content-type': 'text/plain', 'date': 'content-length': '18'} -+-+- b'404 page not found'`

Any Tips how to resolve this are appreciated

**Comment by QU35T-code** [comment]
Same error

**Comment by souzomain** [comment]
hello, the havoc is passing for an unstable moment for 3rd party agents integrations, in dev branch on havoc you can enable the integration, but, while the 3rd party agent integration is not an priority, I'm hoping to be able to continue development.
Thanks @QU35T-code to you contrib
